#cloud-config
package_update: true
package_upgrade: true
runcmd:
    - dnf -y install dnf-plugins-core
    - dnf config-manager --add-repo "https://download.docker.com/linux/fedora/docker-ce.repo"
    - dnf -y install docker-ce java-11-openjdk.x86_64
    - groupadd docker
    - usermod -aG docker $USER
    - systemctl enable --now docker
    - mkdir -p /root/{nomad,consul,vault}
bootcmd:
    - ifdown eth0