#cloud-config
package_update: true
package_upgrade: true
packages:
    - unzip
    - net-tools
    - docker.io
    - openjdk-14-jre-headless
runcmd:
    - mkdir -p /etc/consul.d /opt/consul
    - mkdir -p /etc/nomad.d /opt/nomad
    - mkdir -p /etc/vault.d /opt/vault
write_files:
    - path: /etc/environment
        content: |
            PRIVATE_IP=`ifconfig eth1 | grep 'inet ' | sed 's/\s\s*/ /g' | cut -d' ' -f3 | awk '{ print $1}'`
bootcmd:
    - ifdown eth0
    