#cloud-config
package_update: true
package_upgrade: true
packages:
    - unzip
    - net-tools
    - docker.io
    - openjdk-14-jre-headless
runcmd:
    - [mkdir, -p, /etc/consul.d, /opt/consul]
    - [mkdir, -p, /etc/nomad.d, /opt/nomad]
    - [mkdir, -p, /etc/vault.d, /opt/vault]
bootcmd:
    - ifdown eth0