#cloud-config
package_update: true
package_upgrade: true
packages:
    - unzip
    - net-tools
    - docker.io
    - openjdk-14-jre-headless
runcmd:
    - mkdir -p /root/nomad
    - mkdir -p /root/consul
    - mkdir -p /root/vault
bootcmd:
    - ifdown eth0
    