datacenter       = "solublecode-dc01"
bind_addr        = "__SERVER_IP_PRV__"
data_dir         = "/root/consul"
encrypt          = "kNIf5UjNTxDNAQt+fNC7u1ck2ZRZriVRU+QXhStOrk="
server           = true
bootstrap_expect = __CLUSTER_SIZE__
ui               = true
retry_join       = ["__SERVER_IP_PRV__"]
client_addr      = "0.0.0.0"